### ISSUE TITLE
SDK crashes with ANTS Performance Profiler attached

### ISSUE THREAD

**Issue by deuko** [sportradar/UnifiedOddsSdkNet#17]
Hey, 

I encountered that the latest SDK version 1.27.0 crashes reproducable when the ANTS Performance Profiler is attached (latest version 10.1, any profiling mode), giving the following exception:
`Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Sportradar.OddsFeed.SDK.Common.Internal.ExtensionMethods.WaitAsyncSafe(SemaphoreSlim semaphore)
   at Sportradar.OddsFeed.SDK.Entities.REST.Internal.Caching.SportDataCache.<OnTimerElapsed>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()`

The error is reproducable with the DemoProject:

1. Open the DemoProject and build it
2. Launch ANTS Performance Profiler 10.1
3. Select the *.exe and launch (any profiling mode)
4. Enter "1" and start the "Basic" example within the project
5. SDK Crashes after the feed has been opened

For testing ANTS offers a 14-day trial period, so you don't need a license of course.
If you need any more information please let me know, would be nice if you could fix this problem, as we are using ANTS extensively for profiling our applications.

**Comment by dhrovat** [comment]
Hi,

sorry for late reply :). Today I have tried with ANTS Performance profiler (10.3) and current versions of .net version 1.33.0 and couldnt not reproduced the issue, so hopefully if there was issue in sdk or profiler are resolved.

**Comment by deuko** [comment]
Hey,

thank you for your reply and the testing of the issue.
I also just tested the latest version of ANTS you mentioned with the old version of the SDK 1.27.0 and now it worked, so obviously the issue was at ANTS all the time and it seems they fixed it.
